language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm install jest-cli
  - npm test
env:
  global:
    - CI=true
deploy:
  provider: script
  skip_cleanup: true
  script: git remote add heroku https://heroku:$HEROKU_PRODUCTION_API_KEY@git.heroku.com/thumbtack-clone.git && git push -fq heroku master
  on:
    branch: feature/ci_deployment