language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm install jest-cli
  - npm test
env:
  global:
    - CI=true
before-deploy:
  script:
    - git checkout -- package.json
    - git checkout -- package-lock.json
deploy:
  provider: heroku
  on:
    branch: feature/ci_deployment